[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "termdle"
version = "1.0.0"
description = "A terminal word-guessing game"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "textual",
    "pyfiglet"
]

[project.scripts]
termdle = "termdle.termdle:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
termdle = ["termdle.css", "wordslist.txt", "allowedGuesses.txt"]